[package]
name = "casper-finality-proofs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "test_engine"
path = "bin/test_engine.rs"

[dependencies]
plonky2 = { git = "https://github.com/mir-protocol/plonky2.git", default-features = false }
plonky2x = { git = "https://github.com/succinctlabs/succinctx.git", branch = "main" }
curta = { git = "https://github.com/succinctlabs/curta", branch = "main" }
serde = { version = "1.0.187", features = ["derive"] }
serde_json = "1.0.103"
serde_derive = "1.0.188"
ethers = { version = "2.0" }
primitive-types = "0.12.2"
colored = "2.0.4"
anyhow = "1.0.75"
crossbeam = "0.8.2"
itertools = { version = "0.10.0", default-features = false }
