name: 'Common Setup Steps'
description: 'Checks out the repo and installs dependencies'
inputs:
runs:
  using: 'composite'
  steps:
    - name: Setup Nix
      uses: metacraft-labs/nixos-modules/.github/setup-nix@main
      with:
        trusted-public-keys: ${{ vars.TRUSTED_PUBLIC_KEYS }}
        substituters: ${{ vars.SUBSTITUTERS }}
    - name: Build Nix dev shell
      shell: bash
      run: ./scripts/build-nix-shell.sh
    - name: Install Node.js dependencies
      shell: bash
      run: nix develop -c yarn install --immutable
