compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - code: YN0013
    level: discard
  - code: YN0007
    level: discard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.1.cjs
