compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - code: YN0013
    level: discard
  - code: YN0007
    level: discard

# nodeLinker: node-modules
nodeLinker: pnp
isolatedNixBuilds: ["classic-level", "sqlite3", "bcrypt", "bcrypto", "leveldown", "redis-commander", "secp256k1", "blake-hash", "@chainsafe/blst", "keccak", "@trufflesuite/bigint-buffer", "msgpackr-extract", "bufferutil", "bufferutil", "utf-8-validate", "leveldown"]

plugins:
  - checksum: 262555f70f393385c7b94658bf64e3c673a90cb79b6e3da036c5ff89e2b0133a033c620632b88e1252356926322922deb809aee91bb1c6d1ce0f2d8a4c917480
    path: .yarn/plugins/yarn-plugin-nixify.cjs
    spec: "https://raw.githubusercontent.com/stephank/yarn-plugin-nixify/main/dist/yarn-plugin-nixify.js"

yarnPath: .yarn/releases/yarn-4.1.0.cjs
