logFilters:
  - code: YN0013
    level: discard
  - code: YN0007
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/yarn-plugin-nixify.cjs
    spec: "https://raw.githubusercontent.com/stephank/yarn-plugin-nixify/main/dist/yarn-plugin-nixify.js"

yarnPath: .yarn/releases/yarn-3.6.3.cjs
