logFilters:
  - code: YN0013
    level: discard
  - code: YN0007
    level: discard

# nodeLinker: node-modules
nodeLinker: pnp
isolatedNixBuilds: ["classic-level", "sqlite3", "bcrypt", "bcrypto", "leveldown", "redis-commander", "secp256k1", "blake-hash", "@chainsafe/blst", "keccak", "@trufflesuite/bigint-buffer", "msgpackr-extract", "bufferutil", "bufferutil", "utf-8-validate", "leveldown"]

plugins:
  - path: .yarn/plugins/yarn-plugin-nixify.cjs
    spec: "https://raw.githubusercontent.com/stephank/yarn-plugin-nixify/main/dist/yarn-plugin-nixify.js"

yarnPath: .yarn/releases/yarn-3.6.3.cjs
