processes:
  setup:
    description: setup
    working_dir: ./relay/process-compose-scripts/
    command: ./start-setup.sh

  proverserver_check:
    description: check if proverserver is live
    working_dir: ./relay/process-compose-scripts/
    command: ./check-proverserver.sh
    depends_on:
      setup:
        condition: process_completed

  redis:
    description: redis
    log_location: ./logs/redis.log
    working_dir: ./relay/process-compose-scripts/
    command: ./start-redis.sh
    depends_on:
      setup:
        condition: process_completed
    availability:
      restart: always

  proverserver:
    description: proverserver
    log_location: ./logs/prover_server.log
    working_dir: ./relay/process-compose-scripts/
    command: ./start-proverserver.sh
    depends_on:
      setup:
        condition: process_completed
    availability:
      restart: always

  prometheus:
    description: prometheus
    log_location: ./logs/prometheus.log
    command: ./start-prometheus.sh
    working_dir: ./relay/process-compose-scripts/
    depends_on:
      setup:
        condition: process_completed
    availability:
      restart: always

  pollUpdatesWorker:
    description: pollUpdatesWorker
    log_location: ./logs/pollUpdatesWorker.log
    command: yarn run pollUpdatesWorker
    working_dir: ./relay
    depends_on:
      prometheus:
        condition: process_started
    availability:
      restart: always

  proofGenerationWorker:
    description: proofGenerationWorker
    log_location: ./logs/proofGenerationWorker.log
    command: yarn run proofGenerationWorker --prover ${PROVER_SERVER_HOST}:${PROVER_SERVER_PORT}
    working_dir: ./relay
    depends_on:
      pollUpdatesWorker:
        condition: process_started
    availability:
      restart: always

  cleaner:
    description: cleaner
    log_location: ./logs/cleaner.log
    command: yarn ts ./workers/cleaner.ts
    working_dir: ./relay/workers
    depends_on:
      setup:
        condition: process_completed

  sepolia:
    description: sepolia
    log_location: ./logs/sepolia.log
    command: yarn hardhat start-publishing --lightclient ${LC_SEPOLIA} --network sepolia --follownetwork ${FOLLOW_NETWORK} --slotsjump ${SLOTS_JUMP} --prometheusport 3004
    working_dir: ./beacon-light-client/solidity
    depends_on:
      proverserver_check:
        condition: process_completed

  fantom:
    description: fantom
    log_location: ./logs/fantom.log
    command: yarn hardhat start-publishing --lightclient ${LC_FANTOM} --network fantom --follownetwork ${FOLLOW_NETWORK} --slotsjump ${SLOTS_JUMP} --prometheusport 3007
    working_dir: ./beacon-light-client/solidity
    depends_on:
      proverserver_check:
        condition: process_completed

  alfajores:
    description: alfajores-celo
    log_location: ./logs/alfajores.log
    command: yarn hardhat start-publishing --lightclient ${LC_ALFAJORES} --network celo --follownetwork ${FOLLOW_NETWORK} --slotsjump ${SLOTS_JUMP} --prometheusport 3008
    working_dir: ./beacon-light-client/solidity
    depends_on:
      proverserver_check:
        condition: process_completed

  bsc:
    description: bsc
    log_location: ./logs/bsc.log
    command: yarn hardhat start-publishing --lightclient ${LC_BSC} --network bsc --follownetwork ${FOLLOW_NETWORK} --slotsjump ${SLOTS_JUMP} --prometheusport 3009
    working_dir: ./beacon-light-client/solidity
    depends_on:
      proverserver_check:
        condition: process_completed

  chiado:
    description: chiado
    log_location: ./logs/chiado.log
    command: yarn hardhat start-publishing --lightclient ${LC_CHIADO} --network chiado --follownetwork ${FOLLOW_NETWORK} --slotsjump ${SLOTS_JUMP} --prometheusport 3010
    working_dir: ./beacon-light-client/solidity
    depends_on:
      proverserver_check:
        condition: process_completed

  aurora:
    description: aurora
    log_location: ./logs/aurora.log
    command: yarn hardhat start-publishing --lightclient ${LC_AURORA} --network aurora --follownetwork ${FOLLOW_NETWORK} --slotsjump ${SLOTS_JUMP} --prometheusport 3013
    working_dir: ./beacon-light-client/solidity
    depends_on:
      proverserver_check:
        condition: process_completed

  gnosis:
    description: gnosis
    log_location: ./logs/gnosis.log
    command: yarn hardhat start-publishing --lightclient ${LC_GNOSIS} --network gnosis --follownetwork ${FOLLOW_NETWORK} --slotsjump ${SLOTS_JUMP} --prometheusport 3014
    working_dir: ./beacon-light-client/solidity
    depends_on:
      proverserver_check:
        condition: process_completed

  general_logs:
    description: general_logs
    log_location: ./logs/general_logs.log
    command: yarn ts relayer_logger.ts
    working_dir: ./relay
    depends_on:
      proverserver_check:
        condition: process_completed
