# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "bn254" = super.buildPythonPackage rec {
    pname = "bn254";
    version = "0.1.1";
    src = ./../../../../.cache/pip/wheels/87/30/e7/defe485c4f4ecb75ad89625c432d18d2305156bf8b77a5d9cd/bn254-0.1.1-py3-none-any.whl;
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
