[package]
name = "circuits_executables"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
circuits = { path = "../circuits" }
num = { version = "0.4.0", features = ["serde"] }
plonky2 = { git = "https://github.com/metacraft-labs/plonky2" }
redis = "0.22"
serde = "1.0.164"
serde_json = "1.0.96"
anyhow = "1.0.71"
hex = "0.4.3"
redis-work-queue = "0.1.3"
futures-lite = "1"
jemallocator = "0.5.0"
clap = "3.0"
jsonm = "0.2.0"
serde-binary = "0.5.0"
ssz_rs = "0.9.0"
base64 = "0.21.5"
async-trait = "0.1.74"
tokio = { version = "1.35.1", features = ["full"] }
aws-config = "1.1.1"
aws-sdk-s3 = "1.10.0"
azure_storage_blobs = "0.18.0"
azure_core = "0.18.0"
azure_storage = "0.18.0"
futures = "0.3.30"
dotenv = "0.15.0"

[[bin]]
name = "balance_verification"
path = "bin/balance_verification.rs"

[[bin]]
name = "commitment_mapper"
path = "bin/commitment_mapper.rs"

[[bin]]
name = "balance_verification_circuit_data_generation"
path = "bin/balance_verification_circuit_data_generation.rs"

# [[bin]]
# name = "final_layer"
# path = "bin/final_layer.rs"

[[bin]]
name = "commitment_mapper_circuit_data_generation"
path = "bin/commitment_mapper_circuit_data_generation.rs"
