use num_bigint::BigUint;
use plonky2::field::goldilocks_field::GoldilocksField;
use poseidon_validator_tree::tree::{compute_validators_merkle_proof, Validator};

fn main() {
    const D: usize = 2;
    type F = GoldilocksField;

    let validator = Validator {
        pubkey: [
            true, false, true, true, true, false, false, false, false, false, true, false, false,
            true, false, false, true, false, true, true, false, true, false, true, true, true,
            true, false, true, true, false, true, true, true, true, false, false, false, true,
            true, false, false, true, true, true, false, true, false, false, true, true, true,
            true, false, true, true, false, false, false, false, false, true, false, true, true,
            false, true, false, false, false, true, true, false, true, true, true, true, false,
            false, false, true, false, true, false, true, false, false, false, false, true, false,
            false, true, false, true, true, false, false, false, true, true, false, false, false,
            false, false, true, true, true, false, true, true, false, true, false, false, true,
            false, true, true, true, true, false, false, false, true, true, true, true, true, true,
            false, false, true, true, true, true, true, false, true, true, false, true, true, true,
            false, false, false, true, false, false, true, false, true, false, false, true, true,
            false, false, true, true, true, false, false, true, false, false, true, false, false,
            false, true, false, true, true, false, true, true, false, false, true, false, true,
            true, false, false, true, true, true, true, true, false, false, false, true, false,
            true, false, true, false, false, false, false, true, true, false, false, true, false,
            false, true, false, true, true, true, true, true, false, true, false, false, true,
            true, false, true, false, true, true, false, false, true, true, true, true, false,
            true, true, false, true, true, true, false, false, true, false, true, false, false,
            false, true, false, true, true, true, true, false, true, false, true, false, false,
            false, false, false, false, true, true, false, false, false, false, true, false, false,
            false, false, false, false, true, true, true, false, true, false, true, true, false,
            false, true, true, false, false, true, true, true, true, false, false, false, true,
            true, false, true, false, false, false, true, false, false, true, false, false, false,
            false, false, false, false, false, false, true, true, true, true, false, true, false,
            true, true, false, false, false, false, false, true, false, true, true, true, false,
            true, true, false, false, false, true, true, true, true, true, false, false, true,
            false, true, false, true, true, true, true, true, false, true, false, true, false,
            false, true, true, true, false, false, true, false, true, false, true, true, true,
            true, false, false, true, false,
        ],
        withdrawal_credentials: [
            false, false, false, false, false, false, false, false, false, true, false, true,
            false, false, true, false, true, true, true, true, true, true, true, false, true, true,
            false, true, false, false, true, false, false, true, true, true, true, false, true,
            true, true, false, true, false, true, true, false, true, true, false, true, true, true,
            true, false, true, true, false, true, true, false, true, true, false, false, true,
            true, true, true, true, false, true, false, true, false, true, true, true, false,
            false, true, false, true, false, true, true, false, true, false, true, true, false,
            true, false, true, false, false, true, false, true, true, false, false, true, false,
            false, true, false, true, false, false, true, true, false, true, false, true, true,
            false, false, false, true, false, false, false, true, false, false, true, false, true,
            false, true, false, true, true, true, true, false, true, false, false, false, false,
            false, false, true, true, false, true, false, false, false, true, true, false, true,
            true, true, true, false, true, true, true, false, true, true, false, true, true, true,
            true, false, false, false, false, false, false, false, false, false, true, true, false,
            false, false, false, true, false, false, false, false, false, false, false, false,
            false, false, true, false, true, false, true, false, true, false, true, true, false,
            true, true, true, true, true, false, true, true, true, true, true, false, true, true,
            true, false, true, false, true, false, true, false, true, false, true, false, false,
            true, false, false, false, true, true, false, false, true, true, true, true, false,
            false, true, true, false, false, true, true,
        ],
        effective_balance: BigUint::from(32000000000 as u64),
        slashed: false,
        activation_eligibility_epoch: BigUint::from(0 as u8),
        activation_epoch: BigUint::from(0 as u8),
        exit_epoch: BigUint::from(18446744073709551615 as u64),
        withdrawable_epoch: BigUint::from(18446744073709551615 as u64),
    };

    let validator1 = Validator {
        pubkey: [
            true, false, true, true, true, false, false, false, false, false, true, false, false,
            true, false, false, true, false, true, true, false, true, false, true, true, true,
            true, false, true, true, false, true, true, true, true, false, false, false, true,
            true, false, false, true, true, true, false, true, false, false, true, true, true,
            true, false, true, true, false, false, false, false, false, true, false, true, true,
            false, true, false, false, false, true, true, false, true, true, true, true, false,
            false, false, true, false, true, false, true, false, false, false, false, true, false,
            false, true, false, true, true, false, false, false, true, true, false, false, false,
            false, false, true, true, true, false, true, true, false, true, false, false, true,
            false, true, true, true, true, false, false, false, true, true, true, true, true, true,
            false, false, true, true, true, true, true, false, true, true, false, true, true, true,
            false, false, false, true, false, false, true, false, true, false, false, true, true,
            false, false, true, true, true, false, false, true, false, false, true, false, false,
            false, true, false, true, true, false, true, true, false, false, true, false, true,
            true, false, false, true, true, true, true, true, false, false, false, true, false,
            true, false, true, false, false, false, false, true, true, false, false, true, false,
            false, true, false, true, true, true, true, true, false, true, false, false, true,
            true, false, true, false, true, true, false, false, true, true, true, true, false,
            true, true, false, true, true, true, false, false, true, false, true, false, false,
            false, true, false, true, true, true, true, false, true, false, true, false, false,
            false, false, false, false, true, true, false, false, false, false, true, false, false,
            false, false, false, false, true, true, true, false, true, false, true, true, false,
            false, true, true, false, false, true, true, true, true, false, false, false, true,
            true, false, true, false, false, false, true, false, false, true, false, false, false,
            false, false, false, false, false, false, true, true, true, true, false, true, false,
            true, true, false, false, false, false, false, true, false, true, true, true, false,
            true, true, false, false, false, true, true, true, true, true, false, false, true,
            false, true, false, true, true, true, true, true, false, true, false, true, false,
            false, true, true, true, false, false, true, false, true, false, true, true, true,
            true, false, false, true, false,
        ],
        withdrawal_credentials: [
            false, false, false, false, false, false, false, false, false, true, false, true,
            false, false, true, false, true, true, true, true, true, true, true, false, true, true,
            false, true, false, false, true, false, false, true, true, true, true, false, true,
            true, true, false, true, false, true, true, false, true, true, false, true, true, true,
            true, false, true, true, false, true, true, false, true, true, false, false, true,
            true, true, true, true, false, true, false, true, false, true, true, true, false,
            false, true, false, true, false, true, true, false, true, false, true, true, false,
            true, false, true, false, false, true, false, true, true, false, false, true, false,
            false, true, false, true, false, false, true, true, false, true, false, true, true,
            false, false, false, true, false, false, false, true, false, false, true, false, true,
            false, true, false, true, true, true, true, false, true, false, false, false, false,
            false, false, true, true, false, true, false, false, false, true, true, false, true,
            true, true, true, false, true, true, true, false, true, true, false, true, true, true,
            true, false, false, false, false, false, false, false, false, false, true, true, false,
            false, false, false, true, false, false, false, false, false, false, false, false,
            false, false, true, false, true, false, true, false, true, false, true, true, false,
            true, true, true, true, true, false, true, true, true, true, true, false, true, true,
            true, false, true, false, true, false, true, false, true, false, true, false, false,
            true, false, false, false, true, true, false, false, true, true, true, true, false,
            false, true, true, false, false, true, true,
        ],
        effective_balance: BigUint::from(32000000001 as u64),
        slashed: false,
        activation_eligibility_epoch: BigUint::from(0 as u8),
        activation_epoch: BigUint::from(0 as u8),
        exit_epoch: BigUint::from(18446744073709551615 as u64),
        withdrawable_epoch: BigUint::from(18446744073709551615 as u64),
    };

    let validator2 = Validator {
        pubkey: [
            true, false, true, true, true, false, false, false, false, false, true, false, false,
            true, false, false, true, false, true, true, false, true, false, true, true, true,
            true, false, true, true, false, true, true, true, true, false, false, false, true,
            true, false, false, true, true, true, false, true, false, false, true, true, true,
            true, false, true, true, false, false, false, false, false, true, false, true, true,
            false, true, false, false, false, true, true, false, true, true, true, true, false,
            false, false, true, false, true, false, true, false, false, false, false, true, false,
            false, true, false, true, true, false, false, false, true, true, false, false, false,
            false, false, true, true, true, false, true, true, false, true, false, false, true,
            false, true, true, true, true, false, false, false, true, true, true, true, true, true,
            false, false, true, true, true, true, true, false, true, true, false, true, true, true,
            false, false, false, true, false, false, true, false, true, false, false, true, true,
            false, false, true, true, true, false, false, true, false, false, true, false, false,
            false, true, false, true, true, false, true, true, false, false, true, false, true,
            true, false, false, true, true, true, true, true, false, false, false, true, false,
            true, false, true, false, false, false, false, true, true, false, false, true, false,
            false, true, false, true, true, true, true, true, false, true, false, false, true,
            true, false, true, false, true, true, false, false, true, true, true, true, false,
            true, true, false, true, true, true, false, false, true, false, true, false, false,
            false, true, false, true, true, true, true, false, true, false, true, false, false,
            false, false, false, false, true, true, false, false, false, false, true, false, false,
            false, false, false, false, true, true, true, false, true, false, true, true, false,
            false, true, true, false, false, true, true, true, true, false, false, false, true,
            true, false, true, false, false, false, true, false, false, true, false, false, false,
            false, false, false, false, false, false, true, true, true, true, false, true, false,
            true, true, false, false, false, false, false, true, false, true, true, true, false,
            true, true, false, false, false, true, true, true, true, true, false, false, true,
            false, true, false, true, true, true, true, true, false, true, false, true, false,
            false, true, true, true, false, false, true, false, true, false, true, true, true,
            true, false, false, true, false,
        ],
        withdrawal_credentials: [
            false, false, false, false, false, false, false, false, false, true, false, true,
            false, false, true, false, true, true, true, true, true, true, true, false, true, true,
            false, true, false, false, true, false, false, true, true, true, true, false, true,
            true, true, false, true, false, true, true, false, true, true, false, true, true, true,
            true, false, true, true, false, true, true, false, true, true, false, false, true,
            true, true, true, true, false, true, false, true, false, true, true, true, false,
            false, true, false, true, false, true, true, false, true, false, true, true, false,
            true, false, true, false, false, true, false, true, true, false, false, true, false,
            false, true, false, true, false, false, true, true, false, true, false, true, true,
            false, false, false, true, false, false, false, true, false, false, true, false, true,
            false, true, false, true, true, true, true, false, true, false, false, false, false,
            false, false, true, true, false, true, false, false, false, true, true, false, true,
            true, true, true, false, true, true, true, false, true, true, false, true, true, true,
            true, false, false, false, false, false, false, false, false, false, true, true, false,
            false, false, false, true, false, false, false, false, false, false, false, false,
            false, false, true, false, true, false, true, false, true, false, true, true, false,
            true, true, true, true, true, false, true, true, true, true, true, false, true, true,
            true, false, true, false, true, false, true, false, true, false, true, false, false,
            true, false, false, false, true, true, false, false, true, true, true, true, false,
            false, true, true, false, false, true, true,
        ],
        effective_balance: BigUint::from(32000000002 as u64),
        slashed: false,
        activation_eligibility_epoch: BigUint::from(0 as u8),
        activation_epoch: BigUint::from(0 as u8),
        exit_epoch: BigUint::from(18446744073709551615 as u64),
        withdrawable_epoch: BigUint::from(18446744073709551615 as u64),
    };

    let validator3 = Validator {
        pubkey: [
            true, false, true, true, true, false, false, false, false, false, true, false, false,
            true, false, false, true, false, true, true, false, true, false, true, true, true,
            true, false, true, true, false, true, true, true, true, false, false, false, true,
            true, false, false, true, true, true, false, true, false, false, true, true, true,
            true, false, true, true, false, false, false, false, false, true, false, true, true,
            false, true, false, false, false, true, true, false, true, true, true, true, false,
            false, false, true, false, true, false, true, false, false, false, false, true, false,
            false, true, false, true, true, false, false, false, true, true, false, false, false,
            false, false, true, true, true, false, true, true, false, true, false, false, true,
            false, true, true, true, true, false, false, false, true, true, true, true, true, true,
            false, false, true, true, true, true, true, false, true, true, false, true, true, true,
            false, false, false, true, false, false, true, false, true, false, false, true, true,
            false, false, true, true, true, false, false, true, false, false, true, false, false,
            false, true, false, true, true, false, true, true, false, false, true, false, true,
            true, false, false, true, true, true, true, true, false, false, false, true, false,
            true, false, true, false, false, false, false, true, true, false, false, true, false,
            false, true, false, true, true, true, true, true, false, true, false, false, true,
            true, false, true, false, true, true, false, false, true, true, true, true, false,
            true, true, false, true, true, true, false, false, true, false, true, false, false,
            false, true, false, true, true, true, true, false, true, false, true, false, false,
            false, false, false, false, true, true, false, false, false, false, true, false, false,
            false, false, false, false, true, true, true, false, true, false, true, true, false,
            false, true, true, false, false, true, true, true, true, false, false, false, true,
            true, false, true, false, false, false, true, false, false, true, false, false, false,
            false, false, false, false, false, false, true, true, true, true, false, true, false,
            true, true, false, false, false, false, false, true, false, true, true, true, false,
            true, true, false, false, false, true, true, true, true, true, false, false, true,
            false, true, false, true, true, true, true, true, false, true, false, true, false,
            false, true, true, true, false, false, true, false, true, false, true, true, true,
            true, false, false, true, false,
        ],
        withdrawal_credentials: [
            false, false, false, false, false, false, false, false, false, true, false, true,
            false, false, true, false, true, true, true, true, true, true, true, false, true, true,
            false, true, false, false, true, false, false, true, true, true, true, false, true,
            true, true, false, true, false, true, true, false, true, true, false, true, true, true,
            true, false, true, true, false, true, true, false, true, true, false, false, true,
            true, true, true, true, false, true, false, true, false, true, true, true, false,
            false, true, false, true, false, true, true, false, true, false, true, true, false,
            true, false, true, false, false, true, false, true, true, false, false, true, false,
            false, true, false, true, false, false, true, true, false, true, false, true, true,
            false, false, false, true, false, false, false, true, false, false, true, false, true,
            false, true, false, true, true, true, true, false, true, false, false, false, false,
            false, false, true, true, false, true, false, false, false, true, true, false, true,
            true, true, true, false, true, true, true, false, true, true, false, true, true, true,
            true, false, false, false, false, false, false, false, false, false, true, true, false,
            false, false, false, true, false, false, false, false, false, false, false, false,
            false, false, true, false, true, false, true, false, true, false, true, true, false,
            true, true, true, true, true, false, true, true, true, true, true, false, true, true,
            true, false, true, false, true, false, true, false, true, false, true, false, false,
            true, false, false, false, true, true, false, false, true, true, true, true, false,
            false, true, true, false, false, true, true,
        ],
        effective_balance: BigUint::from(32000000003 as u64),
        slashed: false,
        activation_eligibility_epoch: BigUint::from(0 as u8),
        activation_epoch: BigUint::from(0 as u8),
        exit_epoch: BigUint::from(18446744073709551615 as u64),
        withdrawable_epoch: BigUint::from(18446744073709551615 as u64),
    };

    let validator4 = Validator {
        pubkey: [
            true, false, true, true, true, false, false, false, false, false, true, false, false,
            true, false, false, true, false, true, true, false, true, false, true, true, true,
            true, false, true, true, false, true, true, true, true, false, false, false, true,
            true, false, false, true, true, true, false, true, false, false, true, true, true,
            true, false, true, true, false, false, false, false, false, true, false, true, true,
            false, true, false, false, false, true, true, false, true, true, true, true, false,
            false, false, true, false, true, false, true, false, false, false, false, true, false,
            false, true, false, true, true, false, false, false, true, true, false, false, false,
            false, false, true, true, true, false, true, true, false, true, false, false, true,
            false, true, true, true, true, false, false, false, true, true, true, true, true, true,
            false, false, true, true, true, true, true, false, true, true, false, true, true, true,
            false, false, false, true, false, false, true, false, true, false, false, true, true,
            false, false, true, true, true, false, false, true, false, false, true, false, false,
            false, true, false, true, true, false, true, true, false, false, true, false, true,
            true, false, false, true, true, true, true, true, false, false, false, true, false,
            true, false, true, false, false, false, false, true, true, false, false, true, false,
            false, true, false, true, true, true, true, true, false, true, false, false, true,
            true, false, true, false, true, true, false, false, true, true, true, true, false,
            true, true, false, true, true, true, false, false, true, false, true, false, false,
            false, true, false, true, true, true, true, false, true, false, true, false, false,
            false, false, false, false, true, true, false, false, false, false, true, false, false,
            false, false, false, false, true, true, true, false, true, false, true, true, false,
            false, true, true, false, false, true, true, true, true, false, false, false, true,
            true, false, true, false, false, false, true, false, false, true, false, false, false,
            false, false, false, false, false, false, true, true, true, true, false, true, false,
            true, true, false, false, false, false, false, true, false, true, true, true, false,
            true, true, false, false, false, true, true, true, true, true, false, false, true,
            false, true, false, true, true, true, true, true, false, true, false, true, false,
            false, true, true, true, false, false, true, false, true, false, true, true, true,
            true, false, false, true, false,
        ],
        withdrawal_credentials: [
            false, false, false, false, false, false, false, false, false, true, false, true,
            false, false, true, false, true, true, true, true, true, true, true, false, true, true,
            false, true, false, false, true, false, false, true, true, true, true, false, true,
            true, true, false, true, false, true, true, false, true, true, false, true, true, true,
            true, false, true, true, false, true, true, false, true, true, false, false, true,
            true, true, true, true, false, true, false, true, false, true, true, true, false,
            false, true, false, true, false, true, true, false, true, false, true, true, false,
            true, false, true, false, false, true, false, true, true, false, false, true, false,
            false, true, false, true, false, false, true, true, false, true, false, true, true,
            false, false, false, true, false, false, false, true, false, false, true, false, true,
            false, true, false, true, true, true, true, false, true, false, false, false, false,
            false, false, true, true, false, true, false, false, false, true, true, false, true,
            true, true, true, false, true, true, true, false, true, true, false, true, true, true,
            true, false, false, false, false, false, false, false, false, false, true, true, false,
            false, false, false, true, false, false, false, false, false, false, false, false,
            false, false, true, false, true, false, true, false, true, false, true, true, false,
            true, true, true, true, true, false, true, true, true, true, true, false, true, true,
            true, false, true, false, true, false, true, false, true, false, true, false, false,
            true, false, false, false, true, true, false, false, true, true, true, true, false,
            false, true, true, false, false, true, true,
        ],
        effective_balance: BigUint::from(32000000004 as u64),
        slashed: false,
        activation_eligibility_epoch: BigUint::from(0 as u8),
        activation_epoch: BigUint::from(0 as u8),
        exit_epoch: BigUint::from(18446744073709551615 as u64),
        withdrawable_epoch: BigUint::from(18446744073709551615 as u64),
    };

    let validator5 = Validator {
        pubkey: [
            true, false, true, true, true, false, false, false, false, false, true, false, false,
            true, false, false, true, false, true, true, false, true, false, true, true, true,
            true, false, true, true, false, true, true, true, true, false, false, false, true,
            true, false, false, true, true, true, false, true, false, false, true, true, true,
            true, false, true, true, false, false, false, false, false, true, false, true, true,
            false, true, false, false, false, true, true, false, true, true, true, true, false,
            false, false, true, false, true, false, true, false, false, false, false, true, false,
            false, true, false, true, true, false, false, false, true, true, false, false, false,
            false, false, true, true, true, false, true, true, false, true, false, false, true,
            false, true, true, true, true, false, false, false, true, true, true, true, true, true,
            false, false, true, true, true, true, true, false, true, true, false, true, true, true,
            false, false, false, true, false, false, true, false, true, false, false, true, true,
            false, false, true, true, true, false, false, true, false, false, true, false, false,
            false, true, false, true, true, false, true, true, false, false, true, false, true,
            true, false, false, true, true, true, true, true, false, false, false, true, false,
            true, false, true, false, false, false, false, true, true, false, false, true, false,
            false, true, false, true, true, true, true, true, false, true, false, false, true,
            true, false, true, false, true, true, false, false, true, true, true, true, false,
            true, true, false, true, true, true, false, false, true, false, true, false, false,
            false, true, false, true, true, true, true, false, true, false, true, false, false,
            false, false, false, false, true, true, false, false, false, false, true, false, false,
            false, false, false, false, true, true, true, false, true, false, true, true, false,
            false, true, true, false, false, true, true, true, true, false, false, false, true,
            true, false, true, false, false, false, true, false, false, true, false, false, false,
            false, false, false, false, false, false, true, true, true, true, false, true, false,
            true, true, false, false, false, false, false, true, false, true, true, true, false,
            true, true, false, false, false, true, true, true, true, true, false, false, true,
            false, true, false, true, true, true, true, true, false, true, false, true, false,
            false, true, true, true, false, false, true, false, true, false, true, true, true,
            true, false, false, true, false,
        ],
        withdrawal_credentials: [
            false, false, false, false, false, false, false, false, false, true, false, true,
            false, false, true, false, true, true, true, true, true, true, true, false, true, true,
            false, true, false, false, true, false, false, true, true, true, true, false, true,
            true, true, false, true, false, true, true, false, true, true, false, true, true, true,
            true, false, true, true, false, true, true, false, true, true, false, false, true,
            true, true, true, true, false, true, false, true, false, true, true, true, false,
            false, true, false, true, false, true, true, false, true, false, true, true, false,
            true, false, true, false, false, true, false, true, true, false, false, true, false,
            false, true, false, true, false, false, true, true, false, true, false, true, true,
            false, false, false, true, false, false, false, true, false, false, true, false, true,
            false, true, false, true, true, true, true, false, true, false, false, false, false,
            false, false, true, true, false, true, false, false, false, true, true, false, true,
            true, true, true, false, true, true, true, false, true, true, false, true, true, true,
            true, false, false, false, false, false, false, false, false, false, true, true, false,
            false, false, false, true, false, false, false, false, false, false, false, false,
            false, false, true, false, true, false, true, false, true, false, true, true, false,
            true, true, true, true, true, false, true, true, true, true, true, false, true, true,
            true, false, true, false, true, false, true, false, true, false, true, false, false,
            true, false, false, false, true, true, false, false, true, true, true, true, false,
            false, true, true, false, false, true, true,
        ],
        effective_balance: BigUint::from(32000000005 as u64),
        slashed: false,
        activation_eligibility_epoch: BigUint::from(0 as u8),
        activation_epoch: BigUint::from(0 as u8),
        exit_epoch: BigUint::from(18446744073709551615 as u64),
        withdrawable_epoch: BigUint::from(18446744073709551615 as u64),
    };

    let validator6 = Validator {
        pubkey: [
            true, false, true, true, true, false, false, false, false, false, true, false, false,
            true, false, false, true, false, true, true, false, true, false, true, true, true,
            true, false, true, true, false, true, true, true, true, false, false, false, true,
            true, false, false, true, true, true, false, true, false, false, true, true, true,
            true, false, true, true, false, false, false, false, false, true, false, true, true,
            false, true, false, false, false, true, true, false, true, true, true, true, false,
            false, false, true, false, true, false, true, false, false, false, false, true, false,
            false, true, false, true, true, false, false, false, true, true, false, false, false,
            false, false, true, true, true, false, true, true, false, true, false, false, true,
            false, true, true, true, true, false, false, false, true, true, true, true, true, true,
            false, false, true, true, true, true, true, false, true, true, false, true, true, true,
            false, false, false, true, false, false, true, false, true, false, false, true, true,
            false, false, true, true, true, false, false, true, false, false, true, false, false,
            false, true, false, true, true, false, true, true, false, false, true, false, true,
            true, false, false, true, true, true, true, true, false, false, false, true, false,
            true, false, true, false, false, false, false, true, true, false, false, true, false,
            false, true, false, true, true, true, true, true, false, true, false, false, true,
            true, false, true, false, true, true, false, false, true, true, true, true, false,
            true, true, false, true, true, true, false, false, true, false, true, false, false,
            false, true, false, true, true, true, true, false, true, false, true, false, false,
            false, false, false, false, true, true, false, false, false, false, true, false, false,
            false, false, false, false, true, true, true, false, true, false, true, true, false,
            false, true, true, false, false, true, true, true, true, false, false, false, true,
            true, false, true, false, false, false, true, false, false, true, false, false, false,
            false, false, false, false, false, false, true, true, true, true, false, true, false,
            true, true, false, false, false, false, false, true, false, true, true, true, false,
            true, true, false, false, false, true, true, true, true, true, false, false, true,
            false, true, false, true, true, true, true, true, false, true, false, true, false,
            false, true, true, true, false, false, true, false, true, false, true, true, true,
            true, false, false, true, false,
        ],
        withdrawal_credentials: [
            false, false, false, false, false, false, false, false, false, true, false, true,
            false, false, true, false, true, true, true, true, true, true, true, false, true, true,
            false, true, false, false, true, false, false, true, true, true, true, false, true,
            true, true, false, true, false, true, true, false, true, true, false, true, true, true,
            true, false, true, true, false, true, true, false, true, true, false, false, true,
            true, true, true, true, false, true, false, true, false, true, true, true, false,
            false, true, false, true, false, true, true, false, true, false, true, true, false,
            true, false, true, false, false, true, false, true, true, false, false, true, false,
            false, true, false, true, false, false, true, true, false, true, false, true, true,
            false, false, false, true, false, false, false, true, false, false, true, false, true,
            false, true, false, true, true, true, true, false, true, false, false, false, false,
            false, false, true, true, false, true, false, false, false, true, true, false, true,
            true, true, true, false, true, true, true, false, true, true, false, true, true, true,
            true, false, false, false, false, false, false, false, false, false, true, true, false,
            false, false, false, true, false, false, false, false, false, false, false, false,
            false, false, true, false, true, false, true, false, true, false, true, true, false,
            true, true, true, true, true, false, true, true, true, true, true, false, true, true,
            true, false, true, false, true, false, true, false, true, false, true, false, false,
            true, false, false, false, true, true, false, false, true, true, true, true, false,
            false, true, true, false, false, true, true,
        ],
        effective_balance: BigUint::from(32000000006 as u64),
        slashed: false,
        activation_eligibility_epoch: BigUint::from(0 as u8),
        activation_epoch: BigUint::from(0 as u8),
        exit_epoch: BigUint::from(18446744073709551615 as u64),
        withdrawable_epoch: BigUint::from(18446744073709551615 as u64),
    };

    let validator7 = Validator {
        pubkey: [
            true, false, true, true, true, false, false, false, false, false, true, false, false,
            true, false, false, true, false, true, true, false, true, false, true, true, true,
            true, false, true, true, false, true, true, true, true, false, false, false, true,
            true, false, false, true, true, true, false, true, false, false, true, true, true,
            true, false, true, true, false, false, false, false, false, true, false, true, true,
            false, true, false, false, false, true, true, false, true, true, true, true, false,
            false, false, true, false, true, false, true, false, false, false, false, true, false,
            false, true, false, true, true, false, false, false, true, true, false, false, false,
            false, false, true, true, true, false, true, true, false, true, false, false, true,
            false, true, true, true, true, false, false, false, true, true, true, true, true, true,
            false, false, true, true, true, true, true, false, true, true, false, true, true, true,
            false, false, false, true, false, false, true, false, true, false, false, true, true,
            false, false, true, true, true, false, false, true, false, false, true, false, false,
            false, true, false, true, true, false, true, true, false, false, true, false, true,
            true, false, false, true, true, true, true, true, false, false, false, true, false,
            true, false, true, false, false, false, false, true, true, false, false, true, false,
            false, true, false, true, true, true, true, true, false, true, false, false, true,
            true, false, true, false, true, true, false, false, true, true, true, true, false,
            true, true, false, true, true, true, false, false, true, false, true, false, false,
            false, true, false, true, true, true, true, false, true, false, true, false, false,
            false, false, false, false, true, true, false, false, false, false, true, false, false,
            false, false, false, false, true, true, true, false, true, false, true, true, false,
            false, true, true, false, false, true, true, true, true, false, false, false, true,
            true, false, true, false, false, false, true, false, false, true, false, false, false,
            false, false, false, false, false, false, true, true, true, true, false, true, false,
            true, true, false, false, false, false, false, true, false, true, true, true, false,
            true, true, false, false, false, true, true, true, true, true, false, false, true,
            false, true, false, true, true, true, true, true, false, true, false, true, false,
            false, true, true, true, false, false, true, false, true, false, true, true, true,
            true, false, false, true, false,
        ],
        withdrawal_credentials: [
            false, false, false, false, false, false, false, false, false, true, false, true,
            false, false, true, false, true, true, true, true, true, true, true, false, true, true,
            false, true, false, false, true, false, false, true, true, true, true, false, true,
            true, true, false, true, false, true, true, false, true, true, false, true, true, true,
            true, false, true, true, false, true, true, false, true, true, false, false, true,
            true, true, true, true, false, true, false, true, false, true, true, true, false,
            false, true, false, true, false, true, true, false, true, false, true, true, false,
            true, false, true, false, false, true, false, true, true, false, false, true, false,
            false, true, false, true, false, false, true, true, false, true, false, true, true,
            false, false, false, true, false, false, false, true, false, false, true, false, true,
            false, true, false, true, true, true, true, false, true, false, false, false, false,
            false, false, true, true, false, true, false, false, false, true, true, false, true,
            true, true, true, false, true, true, true, false, true, true, false, true, true, true,
            true, false, false, false, false, false, false, false, false, false, true, true, false,
            false, false, false, true, false, false, false, false, false, false, false, false,
            false, false, true, false, true, false, true, false, true, false, true, true, false,
            true, true, true, true, true, false, true, true, true, true, true, false, true, true,
            true, false, true, false, true, false, true, false, true, false, true, false, false,
            true, false, false, false, true, true, false, false, true, true, true, true, false,
            false, true, true, false, false, true, true,
        ],
        effective_balance: BigUint::from(32000000007 as u64),
        slashed: false,
        activation_eligibility_epoch: BigUint::from(0 as u8),
        activation_epoch: BigUint::from(0 as u8),
        exit_epoch: BigUint::from(18446744073709551615 as u64),
        withdrawable_epoch: BigUint::from(18446744073709551615 as u64),
    };

    let validator8 = Validator {
        pubkey: [
            true, false, true, true, true, false, false, false, false, false, true, false, false,
            true, false, false, true, false, true, true, false, true, false, true, true, true,
            true, false, true, true, false, true, true, true, true, false, false, false, true,
            true, false, false, true, true, true, false, true, false, false, true, true, true,
            true, false, true, true, false, false, false, false, false, true, false, true, true,
            false, true, false, false, false, true, true, false, true, true, true, true, false,
            false, false, true, false, true, false, true, false, false, false, false, true, false,
            false, true, false, true, true, false, false, false, true, true, false, false, false,
            false, false, true, true, true, false, true, true, false, true, false, false, true,
            false, true, true, true, true, false, false, false, true, true, true, true, true, true,
            false, false, true, true, true, true, true, false, true, true, false, true, true, true,
            false, false, false, true, false, false, true, false, true, false, false, true, true,
            false, false, true, true, true, false, false, true, false, false, true, false, false,
            false, true, false, true, true, false, true, true, false, false, true, false, true,
            true, false, false, true, true, true, true, true, false, false, false, true, false,
            true, false, true, false, false, false, false, true, true, false, false, true, false,
            false, true, false, true, true, true, true, true, false, true, false, false, true,
            true, false, true, false, true, true, false, false, true, true, true, true, false,
            true, true, false, true, true, true, false, false, true, false, true, false, false,
            false, true, false, true, true, true, true, false, true, false, true, false, false,
            false, false, false, false, true, true, false, false, false, false, true, false, false,
            false, false, false, false, true, true, true, false, true, false, true, true, false,
            false, true, true, false, false, true, true, true, true, false, false, false, true,
            true, false, true, false, false, false, true, false, false, true, false, false, false,
            false, false, false, false, false, false, true, true, true, true, false, true, false,
            true, true, false, false, false, false, false, true, false, true, true, true, false,
            true, true, false, false, false, true, true, true, true, true, false, false, true,
            false, true, false, true, true, true, true, true, false, true, false, true, false,
            false, true, true, true, false, false, true, false, true, false, true, true, true,
            true, false, false, true, false,
        ],
        withdrawal_credentials: [
            false, false, false, false, false, false, false, false, false, true, false, true,
            false, false, true, false, true, true, true, true, true, true, true, false, true, true,
            false, true, false, false, true, false, false, true, true, true, true, false, true,
            true, true, false, true, false, true, true, false, true, true, false, true, true, true,
            true, false, true, true, false, true, true, false, true, true, false, false, true,
            true, true, true, true, false, true, false, true, false, true, true, true, false,
            false, true, false, true, false, true, true, false, true, false, true, true, false,
            true, false, true, false, false, true, false, true, true, false, false, true, false,
            false, true, false, true, false, false, true, true, false, true, false, true, true,
            false, false, false, true, false, false, false, true, false, false, true, false, true,
            false, true, false, true, true, true, true, false, true, false, false, false, false,
            false, false, true, true, false, true, false, false, false, true, true, false, true,
            true, true, true, false, true, true, true, false, true, true, false, true, true, true,
            true, false, false, false, false, false, false, false, false, false, true, true, false,
            false, false, false, true, false, false, false, false, false, false, false, false,
            false, false, true, false, true, false, true, false, true, false, true, true, false,
            true, true, true, true, true, false, true, true, true, true, true, false, true, true,
            true, false, true, false, true, false, true, false, true, false, true, false, false,
            true, false, false, false, true, true, false, false, true, true, true, true, false,
            false, true, true, false, false, true, true,
        ],
        effective_balance: BigUint::from(32000000008 as u64),
        slashed: false,
        activation_eligibility_epoch: BigUint::from(0 as u8),
        activation_epoch: BigUint::from(0 as u8),
        exit_epoch: BigUint::from(18446744073709551615 as u64),
        withdrawable_epoch: BigUint::from(18446744073709551615 as u64),
    };

    let validator9 = Validator {
        pubkey: [
            true, false, true, true, true, false, false, false, false, false, true, false, false,
            true, false, false, true, false, true, true, false, true, false, true, true, true,
            true, false, true, true, false, true, true, true, true, false, false, false, true,
            true, false, false, true, true, true, false, true, false, false, true, true, true,
            true, false, true, true, false, false, false, false, false, true, false, true, true,
            false, true, false, false, false, true, true, false, true, true, true, true, false,
            false, false, true, false, true, false, true, false, false, false, false, true, false,
            false, true, false, true, true, false, false, false, true, true, false, false, false,
            false, false, true, true, true, false, true, true, false, true, false, false, true,
            false, true, true, true, true, false, false, false, true, true, true, true, true, true,
            false, false, true, true, true, true, true, false, true, true, false, true, true, true,
            false, false, false, true, false, false, true, false, true, false, false, true, true,
            false, false, true, true, true, false, false, true, false, false, true, false, false,
            false, true, false, true, true, false, true, true, false, false, true, false, true,
            true, false, false, true, true, true, true, true, false, false, false, true, false,
            true, false, true, false, false, false, false, true, true, false, false, true, false,
            false, true, false, true, true, true, true, true, false, true, false, false, true,
            true, false, true, false, true, true, false, false, true, true, true, true, false,
            true, true, false, true, true, true, false, false, true, false, true, false, false,
            false, true, false, true, true, true, true, false, true, false, true, false, false,
            false, false, false, false, true, true, false, false, false, false, true, false, false,
            false, false, false, false, true, true, true, false, true, false, true, true, false,
            false, true, true, false, false, true, true, true, true, false, false, false, true,
            true, false, true, false, false, false, true, false, false, true, false, false, false,
            false, false, false, false, false, false, true, true, true, true, false, true, false,
            true, true, false, false, false, false, false, true, false, true, true, true, false,
            true, true, false, false, false, true, true, true, true, true, false, false, true,
            false, true, false, true, true, true, true, true, false, true, false, true, false,
            false, true, true, true, false, false, true, false, true, false, true, true, true,
            true, false, false, true, false,
        ],
        withdrawal_credentials: [
            false, false, false, false, false, false, false, false, false, true, false, true,
            false, false, true, false, true, true, true, true, true, true, true, false, true, true,
            false, true, false, false, true, false, false, true, true, true, true, false, true,
            true, true, false, true, false, true, true, false, true, true, false, true, true, true,
            true, false, true, true, false, true, true, false, true, true, false, false, true,
            true, true, true, true, false, true, false, true, false, true, true, true, false,
            false, true, false, true, false, true, true, false, true, false, true, true, false,
            true, false, true, false, false, true, false, true, true, false, false, true, false,
            false, true, false, true, false, false, true, true, false, true, false, true, true,
            false, false, false, true, false, false, false, true, false, false, true, false, true,
            false, true, false, true, true, true, true, false, true, false, false, false, false,
            false, false, true, true, false, true, false, false, false, true, true, false, true,
            true, true, true, false, true, true, true, false, true, true, false, true, true, true,
            true, false, false, false, false, false, false, false, false, false, true, true, false,
            false, false, false, true, false, false, false, false, false, false, false, false,
            false, false, true, false, true, false, true, false, true, false, true, true, false,
            true, true, true, true, true, false, true, true, true, true, true, false, true, true,
            true, false, true, false, true, false, true, false, true, false, true, false, false,
            true, false, false, false, true, true, false, false, true, true, true, true, false,
            false, true, true, false, false, true, true,
        ],
        effective_balance: BigUint::from(32000000009 as u64),
        slashed: false,
        activation_eligibility_epoch: BigUint::from(0 as u8),
        activation_epoch: BigUint::from(0 as u8),
        exit_epoch: BigUint::from(18446744073709551615 as u64),
        withdrawable_epoch: BigUint::from(18446744073709551615 as u64),
    };

    let _even_validators = vec![
        validator.clone(),
        validator1.clone(),
        validator2.clone(),
        validator3.clone(),
    ];

    let _odd_validators = vec![
        validator.clone(),
        validator1.clone(),
        validator2.clone(),
        validator3.clone(),
        validator4.clone(),
    ];

    let _even_validators_not_power_of_2 = vec![
        validator.clone(),
        validator1.clone(),
        validator2.clone(),
        validator3.clone(),
        validator4.clone(),
        validator5.clone(),
        validator6.clone(),
        validator7.clone(),
        validator8.clone(),
        validator9.clone(),
    ];

    let even_zero_index_depth_two_path =
        compute_validators_merkle_proof::<F, D>(_even_validators, 0, 2);
    println!(
        "zero_index_depth_two_path is: {:?}",
        even_zero_index_depth_two_path.unwrap()
    );

    println!("||||||||||||||||||||||||||||||||||||||||");

    let odd_zero_index_depth_three_path =
        compute_validators_merkle_proof::<F, D>(_odd_validators, 0, 3);
    println!(
        "odd_zero_index_depth_three_path is: {:?}",
        odd_zero_index_depth_three_path.unwrap()
    );

    println!("||||||||||||||||||||||||||||||||||||||||");

    let even_not_power_2_zero_index_depth_four_path =
        compute_validators_merkle_proof::<F, D>(_even_validators_not_power_of_2, 0, 4);
    println!(
        "even_not_power_2_zero_index_depth_four_path is: {:?}",
        even_not_power_2_zero_index_depth_four_path.unwrap()
    );
}
