pub const SLOTS_PER_EPOCH: u64 = 32;
pub const SLOTS_PER_HISTORICAL_ROOT: u64 = 8192;

pub const BEACON_STATE_SLOT_GINDEX: u64 = 34;
pub const BEACON_STATE_PREVIOUS_JUSTIFIED_CHECKPOINT_GINDEX: u64 = 50;
pub const BEACON_STATE_CURRENT_JUSTIFIED_CHECKPOINT_GINDEX: u64 = 51;
pub const BEACON_STATE_JUSTIFICATION_BITS_GINDEX: u64 = 49;
pub const BEACON_STATE_FINALIZED_CHECKPOINT_GINDEX: u64 = 52;
pub const BEACON_STATE_BLOCK_ROOTS_GINDEX: u64 = 37;
pub const DEPTH18_START_BLOCK_ROOTS_GINDEX: u64 = 303104;

pub const VALIDATORS_PER_COMMITTEE: usize = 128; // 2048
pub const VALIDATORS_HASH_TREE_DEPTH: usize = 41;
pub const VALIDATORS_ROOT_PROOF_LEN: usize = 5;
pub const STATE_ROOT_PROOF_LEN: usize = 3;

pub const VERSION_OBJ_BYTES: usize = 4;
