#!/usr/bin/env bash

get_host_system() {
  case "$(uname -s).$(uname -m)" in
    Linux.x86_64)
        system=x86_64-linux
        ;;
    Linux.i?86)
        system=i686-linux
        ;;
    Linux.aarch64)
        system=aarch64-linux
        ;;
    Linux.armv6l_linux)
        system=armv6l-linux
        ;;
    Linux.armv7l_linux)
        system=armv7l-linux
        ;;
    Darwin.x86_64)
        system=x86_64-darwin
        ;;
    Darwin.arm64|Darwin.aarch64)
        system=aarch64-darwin
        ;;
    *) error "sorry, there is no binary distribution of Nix for your platform";;
  esac

  echo "$system"
}
