/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  tutorialSidebar: [
    'intro',
    'why',
    'get-started',

    // --- Use Cases ---
     // Divider
     {
      type: 'html',
      value: '<span class="sidebar-divider" />',
    },
    // Section title
    {
      type: 'html',
      className: 'sidebar-title',
      value: 'Use Cases',
      defaultStyle: true,
    },
    "use-cases/bridge",
    "use-cases/wallet",
    "use-cases/inspiration",
    
    // --- PROTOCOL ---
     // Divider
     {
      type: 'html',
      value: '<span class="sidebar-divider" />',
    },
    // Section title
    {
      type: 'html',
      className: 'sidebar-title',
      value: 'Protocol',
      defaultStyle: true,
    },
   "protocol/overview",
   "protocol/smart-contracts",
   "protocol/circuits",
   "protocol/off-chain",

    // --- RECOURSES ---
    // Divider
    {
      type: 'html',
      value: '<span class="sidebar-divider" />',
    },
    // Section title
    {
      type: 'html',
      className: 'sidebar-title',
      value: 'Resources',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'Concepts',
      items: ['concepts/zkps', "concepts/key-concepts"],
    },
    "resources/deployed",
  ],
};

module.exports = sidebars;
