name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.05

      # TODO Create Cachix Nix binary cache for this project
      # - uses: cachix/cachix-action@v10
      #   with:
      #     name: metacraft-labs-dendreth
      #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build Nix dev shell
        run: nix build '.#devShell.x86_64-linux'
