name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.05
          install_url: https://releases.nixos.org/nix/nix-2.8.1/install

      # TODO Create Cachix Nix binary cache for this project
      # - uses: cachix/cachix-action@v10
      #   with:
      #     name: metacraft-labs-dendreth
      #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build Nix dev shell
        run: nix build '.#devShell.x86_64-linux'

      - name: Install Node.js dependencies
        run: nix develop -c yarn install --immutable

      - name: Run tests
        run: nix develop -c yarn test
