name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # CARGO_NET_GIT_FETCH_WITH_CLI: true
  INFURA_API_KEY: '${{ secrets.INFURA_API_KEY }}'
  USER_PRIVATE_KEY: '${{ secrets.USER_PRIVATE_KEY }}'
  ETHERSCAN_API_KEY: '${{ secrets.ETHERSCAN_API_KEY }}'
  ETHEREUM_MAINNET_RPC: https://eth.llamarpc.com

jobs:
  
  Run_Plonky2_Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use local my-action
        uses: ./.github/actions/setup
        with:
          cachix_auth_token: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Run plonky2 circuit tests
        run: nix develop -c make test-plonky2-circuits

  check:
    if: always()

    needs:
      - Run_Plonky2_Tests

    runs-on: ubuntu-latest

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
