name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  INFURA_API_KEY: '${{ secrets.INFURA_API_KEY }}'
  USER_PRIVATE_KEY: '${{ secrets.USER_PRIVATE_KEY }}'
  ETHERSCAN_API_KEY: '${{ secrets.ETHERSCAN_API_KEY }}'

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: ./.github/actions/build-nix-dev-shell

      - name: Install Node.js dependencies
        run: nix develop -c yarn format:check

      - name: Run Nim Light Client compiled with emsctipten tests
        run: nix develop -c yarn test-emcc

      - name: Run Nim Light Client compiled with clang tests
        run: nix develop -c yarn test
