name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  INFURA_API_KEY: '${{ secrets.INFURA_API_KEY }}'
  USER_PRIVATE_KEY: '${{ secrets.USER_PRIVATE_KEY }}'
  ETHERSCAN_API_KEY: '${{ secrets.ETHERSCAN_API_KEY }}'
  ETHEREUM_MAINNET_RPC: https://eth.llamarpc.com
jobs:
  test:
    strategy:
      matrix:
        jobs:
          - name: Lint
            command: yarn format:check

          - name: Typecheck
            command: yarn check:build

          - name: EOS_Relayer_Test
            command: yarn test './tests/eosLightClient/test-verifier-in-EOS-relay.ts'
            disabled: true

          - name: Solidity_Validators_Accumulator_Test
            command: make test-validator-accumulator

          - name: Nim_Light_Client_Compiled_with_Emsctipten_Tests
            command: yarn test-emcc './tests/test-nim-to-wasm.ts' 'test-nim-light-client.ts'
            disabled: true

          - name: Nim_Light_Client_Clang_Test
            command: yarn test './tests/test-nim-to-wasm.ts' 'test-nim-light-client.ts'

          - name: Nim_Groth16_Verifier_Tests
            command: make test-groth16-verifier

          - name: Run_Light_Client_In_Cosmos_Test
            command: yarn test './tests/cosmosLightClient/test-nim-light-client-in-cosmos.ts'
            disabled: true

          - name: Run_Verifier_In_Cosmos_Test
            command: yarn test './tests/cosmosLightClient/test-verifier-in-cosmos.ts'
            disabled: true

          - name: Run_Verifier_In_Cosmos_Relay_Tests
            command: yarn test './tests/cosmosLightClient/test-verifier-in-cosmos-relay.ts'
            disabled: true

          - name: Run_Circom_Tests
            command: make test-circom-circuits

          - name: Run_Plonky2_Tests
            command: make test-plonky2-circuits

          - name: Run_Verify_Given_Proof
            command: nim c -r 'tests/verify_proof/verify_given_proof_test.nim'

          - name: Run_Verify_Given_Proof_ffJS
            command: yarn test './tests/verify_proof/verify_given_proof_test.ts'

          - name: Solidity_Verifier_Tests
            command: make evm-simulation

          - name: OneShot_Syncing_Simulation
            command: make one-shot-syncing-simulation

          - name: Bash_Scripts_Building_Circom_Circuits
            command: ./scripts/build-circom-compress-circuits.sh

    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12
        if: ${{ runner.environment == 'github-hosted' }}
        with:
          extra-conf: accept-flake-config = true

      - uses: cachix/cachix-action@v15
        with:
          name: ${{ vars.CACHIX_CACHE }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build & activate the Nix Dev Shell
        run: |
          eval "$(nix print-dev-env .#devShells.x86_64-linux.default)"
          env >> "$GITHUB_ENV"

      - name: ${{ matrix.name }}
        run: ${{ matrix.command }}
        continue-on-error: ${{ matrix.disabled }}

  final-success:
    needs: test
    runs-on: self-hosted
    if: success()
    steps:
      - name: All matrix jobs succeeded
        run: echo "All matrix jobs succeeded."
