name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  INFURA_API_KEY: '${{ secrets.INFURA_API_KEY }}'
  USER_PRIVATE_KEY: '${{ secrets.USER_PRIVATE_KEY }}'
  ETHERSCAN_API_KEY: '${{ secrets.ETHERSCAN_API_KEY }}'

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.05
          install_url: https://releases.nixos.org/nix/nix-2.8.1/install

      - uses: cachix/cachix-action@v10
        with:
          name: nix-blockchain-development
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build Nix dev shell
        run: nix build '.#devShell.x86_64-linux'

      - name: Install Node.js dependencies
        run: nix develop -c yarn install --immutable

      - name: Install Node.js dependencies
        run: nix develop -c yarn format:check

      - name: Run emsctipten tests
        run: nix develop -c yarn test-emcc

      #- name: Run tests
      #  run: nix develop -c yarn test
